### PR TITLE
Update for Swift 5.2, NIO 2.15, NIO-SSL 2.7.1

### PR DESCRIPTION
**Pull request by christopherweems**
Fixes changes in syntax of NIO & NIO-SSL.
Disables SwiftSMTPVapor library & tests as it seems `vapor/service` 
requires swift-nio 1.0.0..<2.0.0

### CODE REVIEW

**Comment by christopherweems** [comment]
Thank you for writing this, I made some changes to get it running on current versions of Swift-NIO & Swift-NIO-ssl. If everything checks out and you want to merge the changes, I'll mark the draft as complete.

**Comment by ffried** [comment]
@christopherweems First of all thanks for this! 
Yes, the current "stable" version of Vapor (v3) builds on NIO 1.0. However, Vapor 4 is not far from being released (several release candidates are already out).
I'd like to keep the support for Vapor (since we use this library internally with Vapor). If you don't mind using your fork for a little while longer, I'd update this library for NIO 2.0 (with which I started this library btw. 😉) and Vapor 4 simultaneously. I'd also keep the 1.0 version on a separate branch for a while.
Another option would be to merge this into a new branch for the time being.
Let me know what you think.

**Comment by christopherweems** [comment]
Absolutely! I am fine to keep using it as a fork; just wanted to pass it on if it was any help to you. Cheers!

**Comment by ffried** [comment]
Thanks! I'll let you know here once there is a NIO 2.0 version available!

**Comment by ffried** [comment]
Or actually, you might wanna watch #2 🙂

**Comment by ffried** [comment]
@christopherweems Not sure if you subscribed to #2, thus a quick heads-up here. I've just released a first RC for a version 2.0. You can find details on the [release page](https://github.com/sersoft-gmbh/SwiftSMTP/releases/tag/2.0.0-rc.1.0). There _might_ still be SemVer major (breaking) changes until the finalization of version 2.0, though I expect them to mostly be in the Vapor-part, not the SwiftSMTP "core" part.

If you find anything missing / not working, please let me know in #2 and I'll try to fix it ASAP 🙂

**Pull request closed without merging**
